<a href="https://colab.research.google.com/github/LuscasSkywalka/PyTorch-curso/blob/main/pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

tensor1 = torch.rand((7, 7))
print(tensor1)

tensor([[7.4369e-01, 5.8512e-01, 5.1124e-01, 7.9219e-01, 8.6676e-01, 5.4062e-01,
         4.2389e-01],
        [3.8093e-01, 4.0838e-01, 4.2499e-02, 6.9193e-01, 3.2173e-01, 3.2704e-01,
         8.1458e-01],
        [2.7091e-01, 1.4810e-01, 5.7462e-01, 5.6666e-01, 4.6400e-01, 8.6480e-01,
         6.6571e-02],
        [4.3511e-01, 2.9005e-01, 6.6187e-01, 6.7058e-01, 2.0551e-01, 7.2734e-01,
         7.1661e-01],
        [4.5110e-01, 1.2981e-01, 8.5306e-02, 3.6222e-01, 9.7467e-01, 8.0418e-01,
         9.4977e-01],
        [6.9640e-01, 5.2603e-01, 2.3072e-01, 5.4233e-01, 2.6858e-02, 3.2782e-01,
         7.4531e-01],
        [4.8884e-01, 2.6393e-01, 9.7319e-01, 5.2503e-01, 5.2767e-01, 4.3052e-04,
         9.3054e-01]])


In [ ]:
tensor2 = torch.rand((1, 7))
result = torch.matmul(tensor1, tensor2.T)  # Shape: (7, 1)
print(result)

tensor([[2.3098],
        [1.9456],
        [1.2986],
        [2.0338],
        [2.1159],
        [1.9474],
        [2.0776]])


In [ ]:
torch.manual_seed(0)

tensor1_seeded = torch.rand((7, 7))
tensor2_seeded = torch.rand((1, 7))
result_seeded = torch.matmul(tensor1_seeded, tensor2_seeded.T)
print(tensor1_seeded)
print(tensor2_seeded)
print(result_seeded)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [ ]:
torch.cuda.manual_seed(1234)



In [ ]:
torch.manual_seed(1234)

tensor_a = torch.rand((2, 3)).cuda()
tensor_b = torch.rand((2, 3)).cuda()
print(tensor_a)
print(tensor_b)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [ ]:
result_gpu = torch.matmul(tensor_a, tensor_b.T)  # Shape: (2, 2)
print(result_gpu)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [ ]:
max_val = torch.max(result_gpu)
min_val = torch.min(result_gpu)
print(max_val, min_val)

tensor(0.5617, device='cuda:0') tensor(0.3647, device='cuda:0')


In [ ]:
max_index = torch.argmax(result_gpu)
min_index = torch.argmin(result_gpu)
print(max_index, min_index)

tensor(3, device='cuda:0') tensor(0, device='cuda:0')


In [ ]:
torch.manual_seed(7)
tensor_4d = torch.rand((1, 1, 1, 10))
tensor_squeezed = tensor_4d.squeeze()

print("Original tensor:", tensor_4d)
print("Original shape:", tensor_4d.shape)
print("Squeezed tensor:", tensor_squeezed)
print("Squeezed shape:", tensor_squeezed.shape)


Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original shape: torch.Size([1, 1, 1, 10])
Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed shape: torch.Size([10])
